### ISSUE TITLE
typo in module name?

### ISSUE THREAD

**Issue by beenotung** [Stradivario/gapi-orbitdb#1]
shoudn't `OribtDbModule` be `OrbitDbModule`?

**Comment by Stradivario** [comment]
@beenotung Correct!! It will be fixed in 1.2.55 :) 

Thank you man! I appreciate it !

Need more people like you !! :)

**Comment by Stradivario** [comment]
@beenotung fixed!

https://github.com/Stradivario/gapi-orbitdb/blob/master/development/index.ts

**Comment by Stradivario** [comment]
@beenotung Hey man i just want to let you know that today i decided to create first decentralized module inside gapi infrastructure.

Refresh again gapi-orbitdb to see the details.

Install @rxdi/core globally
```bash
npm i @rxdi/core -g
```
Now you have `rxdi` command globally then install this module:
```bash
rxdi i QmWxi1tiVRJfVCTkFD9upaeQoPgG4NzbagxyA1RQCt3X3P
```
Link to module: [QmWxi1tiVRJfVCTkFD9upaeQoPgG4NzbagxyA1RQCt3X3P](https://ipfs.io/ipfs/QmWxi1tiVRJfVCTkFD9upaeQoPgG4NzbagxyA1RQCt3X3P)

It will install also dependencies !

Regards! :))
